--[[
   IoBT Configuration (DATA ONLY)
   Generated by IoBT-Viz Config GUI
   Date: 2026-01-29 10:18:38

   Nodes: 50 (70% infantry, 30% vehicles)
   Communication Range: 4 cells
   DAG: 3 levels, 2 branches (15 tasks)
   Task Duration: 75 ticks per task
   Transfer Duration: 50 ticks (cyan link highlight)
   Simulation: 60 seconds
   Partition Mode: True

   Mobility Pattern: PARTITION MODE (guaranteed stall demo)
   - All units start clustered at map center
   - FAST dispersal (~2 seconds) creates left/right split BEFORE T0 completes
   - Left half and right half end up > comm_range apart (guaranteed partition)
   - Baseline mode (B) will stall waiting for reconnection
   - Smart-Resilient mode (S) will reassign tasks to parent's partition
   - Press S to fix stalls, B to see baseline behavior

   NOTE: Execution logic is in iobt-main.lua (not here).
   This file defines data only: units, buildings, dagTasks, network settings.
]]
IoBTConfig = {
    ticksPerSecond = 25,

    export = {
        enabled = true,
        sampleInterval = 125,  -- Every 5 seconds
        stopAfterTicks = 1500,  -- 60 seconds
    },

    networkSettings = {
        range = 4,
        maxDataRate = 100,
        minDataRate = 10,
    },

    dagSettings = {
        taskDuration = 75,  -- ticks per task
        transferDuration = 50,  -- ticks for transfer visualization
    },

    units = {},

    buildings = {
        -- Power plants to avoid low power warning
        { id = "power1", type = "powr", owner = "Blue", x = 74, y = 76 },
        { id = "power2", type = "powr", owner = "Blue", x = 54, y = 76 },
        -- Command bases
        { id = "hq1", type = "dome", owner = "Blue", x = 74, y = 74 },
        { id = "hq2", type = "dome", owner = "Blue", x = 54, y = 74 },
        { id = "base1", type = "fact", owner = "Blue", x = 74, y = 70 },
        { id = "base2", type = "fact", owner = "Blue", x = 54, y = 70 },
    },

    networkLinks = {},

    dagTasks = {
        { id = "T0", name = "Task 0", deps = {} },
        { id = "T1", name = "Task 1", deps = {"T0"} },
        { id = "T2", name = "Task 2", deps = {"T1"} },
        { id = "T3", name = "Task 3", deps = {"T2"} },
        { id = "T4", name = "Task 4", deps = {"T2"} },
        { id = "T5", name = "Task 5", deps = {"T1"} },
        { id = "T6", name = "Task 6", deps = {"T5"} },
        { id = "T7", name = "Task 7", deps = {"T5"} },
        { id = "T8", name = "Task 8", deps = {"T0"} },
        { id = "T9", name = "Task 9", deps = {"T8"} },
        { id = "T10", name = "Task 10", deps = {"T9"} },
        { id = "T11", name = "Task 11", deps = {"T9"} },
        { id = "T12", name = "Task 12", deps = {"T8"} },
        { id = "T13", name = "Task 13", deps = {"T12"} },
        { id = "T14", name = "Task 14", deps = {"T12"} },
    }
}
-- Helper to add infantry squad (rifle soldiers only - e1)
local function addInfantrySquad(squadId, squadSize, startX, startY, waypoints)
    for i = 1, squadSize do
        local offsetX = (i % 5) - 2  -- Spread in a 5-wide formation
        local offsetY = math.floor(i / 5)
        local unit = {
            id = "inf_" .. squadId .. "_" .. i,
            type = "e1",  -- Rifle infantry only
            owner = "Blue",
            waypoints = {}
        }
        for _, wp in ipairs(waypoints) do
            table.insert(unit.waypoints, {
                time = wp.time + (i * 2),  -- Slight time offset per soldier
                x = math.max(51, math.min(77, wp.x + offsetX)),
                y = math.max(49, math.min(78, wp.y + offsetY))
            })
        end
        table.insert(IoBTConfig.units, unit)
    end
end

-- Helper to add vehicle group
local function addVehicleGroup(groupId, groupSize, unitType, waypoints)
    for i = 1, groupSize do
        local offsetX = (i % 3) - 1  -- Spread in a 3-wide formation
        local offsetY = math.floor(i / 3) * 2
        local unit = {
            id = "veh_" .. groupId .. "_" .. i,
            type = unitType,
            owner = "Blue",
            waypoints = {}
        }
        for _, wp in ipairs(waypoints) do
            table.insert(unit.waypoints, {
                time = wp.time + (i * 5),  -- Slight time offset per vehicle
                x = math.max(51, math.min(77, wp.x + offsetX)),
                y = math.max(49, math.min(78, wp.y + offsetY))
            })
        end
        table.insert(IoBTConfig.units, unit)
    end
end

-- INFANTRY SQUADS (PARTITION MODE: fast dispersal to create left/right split)

-- Squad 1: 7 infantry
addInfantrySquad(1, 7, 63, 62, {
    { time = 0, x = 63, y = 62 },
    { time = 260, x = 63, y = 62 },
    { time = 320, x = 53, y = 62 },
    { time = 600, x = 53, y = 59 },
    { time = 1050, x = 57, y = 62 }
})

-- Squad 2: 7 infantry
addInfantrySquad(2, 7, 64, 62, {
    { time = 0, x = 64, y = 62 },
    { time = 265, x = 64, y = 62 },
    { time = 325, x = 74, y = 62 },
    { time = 600, x = 77, y = 59 },
    { time = 1050, x = 70, y = 66 }
})

-- Squad 3: 7 infantry
addInfantrySquad(3, 7, 65, 62, {
    { time = 0, x = 65, y = 62 },
    { time = 270, x = 65, y = 62 },
    { time = 330, x = 55, y = 63 },
    { time = 600, x = 52, y = 60 },
    { time = 1050, x = 55, y = 59 }
})

-- Squad 4: 7 infantry
addInfantrySquad(4, 7, 63, 63, {
    { time = 0, x = 63, y = 63 },
    { time = 275, x = 63, y = 63 },
    { time = 335, x = 73, y = 63 },
    { time = 600, x = 73, y = 60 },
    { time = 1050, x = 77, y = 63 }
})

-- Squad 5: 7 infantry
addInfantrySquad(5, 7, 64, 63, {
    { time = 0, x = 64, y = 63 },
    { time = 280, x = 64, y = 63 },
    { time = 340, x = 54, y = 64 },
    { time = 600, x = 57, y = 61 },
    { time = 1050, x = 51, y = 68 }
})

-- VEHICLE GROUPS (PARTITION MODE: fast dispersal with infantry)

-- Group 1: 3 jeep
addVehicleGroup(1, 3, "jeep", {
    { time = 0, x = 64, y = 63 },
    { time = 258, x = 64, y = 63 },
    { time = 303, x = 55, y = 64 },
    { time = 600, x = 55, y = 61 },
    { time = 1050, x = 59, y = 64 }
})

-- Group 2: 3 apc
addVehicleGroup(2, 3, "apc", {
    { time = 0, x = 65, y = 63 },
    { time = 263, x = 65, y = 63 },
    { time = 308, x = 76, y = 64 },
    { time = 600, x = 77, y = 61 },
    { time = 1050, x = 72, y = 68 }
})

-- Group 3: 3 1tnk
addVehicleGroup(3, 3, "1tnk", {
    { time = 0, x = 66, y = 63 },
    { time = 268, x = 66, y = 63 },
    { time = 313, x = 57, y = 65 },
    { time = 600, x = 54, y = 62 },
    { time = 1050, x = 57, y = 61 }
})

-- Group 4: 3 2tnk
addVehicleGroup(4, 3, "2tnk", {
    { time = 0, x = 64, y = 64 },
    { time = 273, x = 64, y = 64 },
    { time = 318, x = 75, y = 65 },
    { time = 600, x = 75, y = 62 },
    { time = 1050, x = 77, y = 65 }
})

-- Group 5: 3 3tnk
addVehicleGroup(5, 3, "3tnk", {
    { time = 0, x = 65, y = 64 },
    { time = 278, x = 65, y = 64 },
    { time = 323, x = 56, y = 66 },
    { time = 600, x = 59, y = 63 },
    { time = 1050, x = 52, y = 70 }
})
