--[[
   IoBT Main Visualization Script

   This script implements:
   - Time-waypoint interpolation for unit movement
   - Building placement
   - Position recording and export
   - DAG execution with SAGA scheduler integration
   - Network-aware task scheduling

   The DAG structure is defined in iobt-config.lua (generated by config GUI).
   This file contains all execution logic and SAGA integration.
]]

-- State tracking
IoBTState = {
    units = {},
    buildings = {},
    initialized = false
}

-- Position log for export
PositionLog = {}

-- Linear interpolation helper
function Lerp(a, b, t)
    return a + (b - a) * t
end

-- Get interpolated target position for a unit at current game time
-- Returns nil if the unit shouldn't exist yet (before first waypoint)
function GetInterpolatedPosition(waypoints, currentTime)
    -- Not yet at first waypoint
    if currentTime < waypoints[1].time then
        return nil
    end

    -- Find the waypoint segment we're in
    for i = 1, #waypoints - 1 do
        local wp1 = waypoints[i]
        local wp2 = waypoints[i + 1]

        if currentTime >= wp1.time and currentTime < wp2.time then
            -- Interpolate between waypoints
            local duration = wp2.time - wp1.time
            local elapsed = currentTime - wp1.time
            local t = elapsed / duration

            local x = math.floor(Lerp(wp1.x, wp2.x, t) + 0.5)
            local y = math.floor(Lerp(wp1.y, wp2.y, t) + 0.5)

            return CPos.New(x, y)
        end
    end

    -- Past the last waypoint - stay at final position
    local lastWp = waypoints[#waypoints]
    return CPos.New(lastWp.x, lastWp.y)
end

-- Record current positions of all tracked units
function RecordPositions(currentTime)
    for id, state in pairs(IoBTState.units) do
        if state.actor and not state.actor.IsDead then
            local pos = state.actor.Location
            table.insert(PositionLog, {
                time = currentTime,
                unit = id,
                x = pos.X,
                y = pos.Y
            })
        end
    end
end

-- Export recorded positions as CSV to console
function ExportLog()
    print("=== IOBT POSITION LOG START ===")
    print("time,unit,x,y")
    for _, entry in ipairs(PositionLog) do
        print(entry.time .. "," .. entry.unit .. "," .. entry.x .. "," .. entry.y)
    end
    print("=== IOBT POSITION LOG END ===")
    print("Total entries: " .. #PositionLog)
end

-- ============================================
-- DAG Execution Logic with SAGA Integration
-- ============================================

-- Track DAG execution state
-- Note: transferDuration and taskDuration can be overridden by IoBTConfig.dagSettings
ConfiguredDagState = {
    started = false,
    completedTasks = {},
    runningTasks = {},      -- taskId -> true for currently running
    stalledTasks = {},      -- taskId -> true for connectivity-blocked
    taskNodeAssignment = {}, -- taskId -> nodeIndex that ran/is running the task
    pendingTransfers = {},  -- taskId -> list of pending incoming transfers
    transferDuration = 50,  -- default: ticks for data transfer visualization
    taskDuration = 75,      -- default: ticks per task
    -- SAGA scheduling state
    sagaScheduleRequested = false,
    sagaScheduleReceived = false,
    sagaMonitorCount = 0,
    useSagaScheduler = true  -- Set to false to force round-robin
}

-- Apply settings from IoBTConfig.dagSettings if available
function ApplyDagSettings()
    if IoBTConfig and IoBTConfig.dagSettings then
        if IoBTConfig.dagSettings.taskDuration then
            ConfiguredDagState.taskDuration = IoBTConfig.dagSettings.taskDuration
        end
        if IoBTConfig.dagSettings.transferDuration then
            ConfiguredDagState.transferDuration = IoBTConfig.dagSettings.transferDuration
        end
        print("IoBT DAG: Using config settings - taskDuration=" .. ConfiguredDagState.taskDuration ..
              ", transferDuration=" .. ConfiguredDagState.transferDuration)
    end
end

-- Initialize the configured DAG (reads from IoBTConfig.dagTasks)
function InitConfiguredDag()
    if ConfiguredDagState.started then return end

    -- Apply dag settings from config if available
    ApplyDagSettings()

    -- Check if config has DAG tasks
    if not IoBTConfig.dagTasks or #IoBTConfig.dagTasks == 0 then
        print("IoBT DAG: No tasks defined in IoBTConfig.dagTasks")
        return
    end

    local nodeCount = Blue.GetComputeNodeCount()
    print("IoBT DAG: Found " .. nodeCount .. " compute nodes")
    print("IoBT DAG: Found " .. #IoBTConfig.dagTasks .. " tasks in config")

    if nodeCount < 1 then
        print("IoBT DAG: Need at least 1 compute node")
        return
    end

    ConfiguredDagState.started = true
    ConfiguredDagState.completedTasks = {}
    ConfiguredDagState.runningTasks = {}
    ConfiguredDagState.stalledTasks = {}
    ConfiguredDagState.taskNodeAssignment = {}
    ConfiguredDagState.pendingTransfers = {}
    ConfiguredDagState.sagaScheduleRequested = false
    ConfiguredDagState.sagaScheduleReceived = false
    ConfiguredDagState.sagaMonitorCount = 0
    print("IoBT DAG: Starting configured DAG execution...")

    -- Register all tasks with the DAG system (read from config)
    for _, task in ipairs(IoBTConfig.dagTasks) do
        local depsStr = table.concat(task.deps or {}, ",")
        Blue.AddDagTask(task.id, task.name, depsStr)
    end

    -- Check if SAGA scheduler is available and enabled
    if ConfiguredDagState.useSagaScheduler and Blue.IsBridgeRunning() and Blue.GetBridgeConnectionCount() > 0 then
        print("IoBT DAG: SAGA scheduler connected, requesting schedule...")
        RequestSagaSchedule()
        StartScheduleMonitor()
    else
        if ConfiguredDagState.useSagaScheduler then
            print("IoBT DAG: SAGA not connected (bridge=" .. tostring(Blue.IsBridgeRunning()) ..
                  ", clients=" .. Blue.GetBridgeConnectionCount() .. "), using round-robin")
        else
            print("IoBT DAG: SAGA disabled, using round-robin")
        end
        Blue.SetSchedulerAlgorithm("Round-Robin")
        FallbackAssignTaskNodes()
        ExecuteNextDagTasks()
    end

    -- Start periodic connectivity check for stalled tasks
    StartConnectivityMonitor()
end

-- ============================================
-- SAGA Scheduler Integration
-- ============================================

-- Simple JSON encoder for Lua tables
function EncodeJson(value, indent)
    indent = indent or ""
    local valueType = type(value)

    if valueType == "nil" then
        return "null"
    elseif valueType == "boolean" then
        return value and "true" or "false"
    elseif valueType == "number" then
        return tostring(value)
    elseif valueType == "string" then
        local escaped = value:gsub('\\', '\\\\'):gsub('"', '\\"'):gsub('\n', '\\n'):gsub('\r', '\\r'):gsub('\t', '\\t')
        return '"' .. escaped .. '"'
    elseif valueType == "table" then
        local isArray = true
        local maxIndex = 0
        for k, v in pairs(value) do
            if type(k) ~= "number" or k < 1 or math.floor(k) ~= k then
                isArray = false
                break
            end
            if k > maxIndex then maxIndex = k end
        end
        if maxIndex ~= #value then isArray = false end

        if isArray then
            local parts = {}
            for i, v in ipairs(value) do
                table.insert(parts, EncodeJson(v, indent))
            end
            return "[" .. table.concat(parts, ",") .. "]"
        else
            local parts = {}
            for k, v in pairs(value) do
                local key = type(k) == "string" and k or tostring(k)
                table.insert(parts, '"' .. key .. '":' .. EncodeJson(v, indent))
            end
            return "{" .. table.concat(parts, ",") .. "}"
        end
    end
    return "null"
end

-- Build DAG JSON for SAGA scheduler (reads from IoBTConfig.dagTasks)
function BuildDagJson()
    local nodeCount = Blue.GetComputeNodeCount()

    local dag = {
        tasks = {},
        edges = {},
        compute_nodes = nodeCount,
        task_duration = ConfiguredDagState.taskDuration,
        transfer_duration = ConfiguredDagState.transferDuration
    }

    -- Add tasks with compute cost (read from config)
    for _, task in ipairs(IoBTConfig.dagTasks) do
        table.insert(dag.tasks, {
            id = task.id,
            name = task.name,
            compute_cost = task.computeCost or ConfiguredDagState.taskDuration
        })
    end

    -- Add edges (dependencies) with data size
    for _, task in ipairs(IoBTConfig.dagTasks) do
        for _, dep in ipairs(task.deps or {}) do
            table.insert(dag.edges, {
                source = dep,
                target = task.id,
                data_size = task.dataSize or ConfiguredDagState.transferDuration
            })
        end
    end

    return EncodeJson(dag)
end

-- Request schedule from SAGA service
function RequestSagaSchedule()
    if ConfiguredDagState.sagaScheduleRequested then
        return
    end

    local dagJson = BuildDagJson()
    print("IoBT DAG: Sending schedule request to SAGA...")

    Blue.RequestSchedule(dagJson)
    ConfiguredDagState.sagaScheduleRequested = true
end

-- Fallback to round-robin assignment when SAGA not available
function FallbackAssignTaskNodes()
    local nodeCount = Blue.GetComputeNodeCount()
    local nodeIndex = 0

    for _, task in ipairs(IoBTConfig.dagTasks) do
        local taskId = task.id
        if ConfiguredDagState.taskNodeAssignment[taskId] == nil then
            local assignedNode = nodeIndex % nodeCount
            nodeIndex = nodeIndex + 1
            ConfiguredDagState.taskNodeAssignment[taskId] = assignedNode
        end
    end
end

-- Monitor for SAGA schedule response
function StartScheduleMonitor()
    Trigger.AfterDelay(5, function()
        if not ConfiguredDagState.started then return end
        if ConfiguredDagState.sagaScheduleReceived then return end

        -- Check if SAGA response arrived
        if Blue.HasPendingSchedule() then
            print("IoBT DAG: SAGA schedule response received!")
            ApplySagaAssignments()
            return
        end

        -- Timeout after ~5 seconds (125 ticks at 25 tps)
        ConfiguredDagState.sagaMonitorCount = ConfiguredDagState.sagaMonitorCount + 1
        if ConfiguredDagState.sagaMonitorCount > 25 then
            print("IoBT DAG: SAGA timeout, falling back to round-robin")
            Blue.SetSchedulerAlgorithm("Round-Robin (timeout)")
            Blue.ClearPendingSchedule()
            FallbackAssignTaskNodes()
            ExecuteNextDagTasks()
            return
        end

        -- Continue monitoring
        StartScheduleMonitor()
    end)
end

-- Apply assignments from SAGA schedule response
function ApplySagaAssignments()
    local assignmentsStr = Blue.GetAllPendingAssignments()
    print("IoBT DAG: Raw assignments from SAGA: " .. assignmentsStr)

    if assignmentsStr == "" then
        print("IoBT DAG: No assignments from SAGA, using fallback")
        Blue.SetSchedulerAlgorithm("Round-Robin (empty)")
        FallbackAssignTaskNodes()
        ExecuteNextDagTasks()
        return
    end

    -- Parse "taskId:nodeIndex,taskId:nodeIndex,..." format
    local assignmentCount = 0
    for pair in string.gmatch(assignmentsStr, "[^,]+") do
        local taskId, nodeIndexStr = string.match(pair, "([^:]+):(%d+)")
        if taskId and nodeIndexStr then
            local nodeIndex = tonumber(nodeIndexStr)
            ConfiguredDagState.taskNodeAssignment[taskId] = nodeIndex
            print("IoBT DAG: SAGA assigned " .. taskId .. " to C" .. nodeIndex)
            assignmentCount = assignmentCount + 1
        end
    end

    if assignmentCount > 0 then
        print("IoBT DAG: Applied " .. assignmentCount .. " SAGA assignments")
        Blue.SetSchedulerAlgorithm("SAGA (HEFT)")
        ConfiguredDagState.sagaScheduleReceived = true
    else
        print("IoBT DAG: Failed to parse SAGA assignments, using fallback")
        Blue.SetSchedulerAlgorithm("Round-Robin (parse error)")
        FallbackAssignTaskNodes()
    end

    -- Now start executing tasks
    ExecuteNextDagTasks()
end

-- ============================================
-- DAG Execution Functions
-- ============================================

-- Check if a task's dependencies are satisfied (all completed)
function AreDependenciesSatisfied(taskId)
    for _, task in ipairs(IoBTConfig.dagTasks) do
        if task.id == taskId then
            for _, dep in ipairs(task.deps or {}) do
                if not ConfiguredDagState.completedTasks[dep] then
                    return false
                end
            end
            return true
        end
    end
    return true
end

-- Check if all parent task nodes are connected to the target node
function CanAssignToNode(taskId, targetNode)
    for _, task in ipairs(IoBTConfig.dagTasks) do
        if task.id == taskId then
            for _, dep in ipairs(task.deps or {}) do
                local parentNode = ConfiguredDagState.taskNodeAssignment[dep]
                if parentNode ~= nil then
                    if not Blue.AreNodesConnected(parentNode, targetNode) then
                        return false, dep, parentNode
                    end
                end
            end
            return true, nil, nil
        end
    end
    return true, nil, nil
end

-- Pre-assign nodes to tasks using round-robin (fallback)
function PreAssignTaskNodes()
    local nodeCount = Blue.GetComputeNodeCount()
    local nodeIndex = 0

    for _, task in ipairs(IoBTConfig.dagTasks) do
        local taskId = task.id
        if ConfiguredDagState.taskNodeAssignment[taskId] == nil then
            local assignedNode = nodeIndex % nodeCount
            nodeIndex = nodeIndex + 1
            ConfiguredDagState.taskNodeAssignment[taskId] = assignedNode
        end
    end
end

-- Find and execute tasks that are ready
function ExecuteNextDagTasks()
    local nodeCount = Blue.GetComputeNodeCount()

    -- If using SAGA and haven't received schedule yet, wait
    if ConfiguredDagState.useSagaScheduler and ConfiguredDagState.sagaScheduleRequested and not ConfiguredDagState.sagaScheduleReceived then
        print("IoBT DAG: Waiting for SAGA schedule...")
        return
    end

    -- Pre-assign any remaining tasks
    PreAssignTaskNodes()

    for _, task in ipairs(IoBTConfig.dagTasks) do
        local taskId = task.id

        local shouldSkip = ConfiguredDagState.completedTasks[taskId] or
                          ConfiguredDagState.runningTasks[taskId] or
                          ConfiguredDagState.stalledTasks[taskId]

        if not shouldSkip then
            if AreDependenciesSatisfied(taskId) then
                local assignedNode = ConfiguredDagState.taskNodeAssignment[taskId]
                local canAssign, blockedBy, blockedNode = CanAssignToNode(taskId, assignedNode)

                if canAssign then
                    print("IoBT DAG: Assigning " .. taskId .. " to node C" .. assignedNode)
                    Blue.AssignTask(taskId, assignedNode)
                    ConfiguredDagState.runningTasks[taskId] = true

                    local taskDuration = ConfiguredDagState.taskDuration
                    Trigger.AfterDelay(taskDuration, function()
                        CompleteTask(taskId)
                    end)
                else
                    print("IoBT DAG: Task " .. taskId .. " stalled - C" .. assignedNode ..
                          " disconnected from parent " .. blockedBy .. " (C" .. blockedNode .. ")")
                    Blue.StallTask(taskId)
                    ConfiguredDagState.stalledTasks[taskId] = true
                end
            end
        end
    end
end

-- Periodically check if stalled tasks can resume
function StartConnectivityMonitor()
    Trigger.AfterDelay(25, function()
        if not ConfiguredDagState.started then return end

        for taskId, _ in pairs(ConfiguredDagState.stalledTasks) do
            local targetNode = ConfiguredDagState.taskNodeAssignment[taskId]
            if targetNode then
                local canAssign, _, _ = CanAssignToNode(taskId, targetNode)
                if canAssign then
                    print("IoBT DAG: Task " .. taskId .. " connectivity restored, resuming on C" .. targetNode)
                    Blue.UnstallTask(taskId)
                    ConfiguredDagState.stalledTasks[taskId] = nil

                    Blue.AssignTask(taskId, targetNode)
                    ConfiguredDagState.runningTasks[taskId] = true

                    local taskDuration = ConfiguredDagState.taskDuration
                    Trigger.AfterDelay(taskDuration, function()
                        CompleteTask(taskId)
                    end)
                end
            end
        end

        StartConnectivityMonitor()
    end)
end

-- Find all tasks that depend on the given task
function FindDependentTasks(completedTaskId)
    local dependents = {}
    for _, task in ipairs(IoBTConfig.dagTasks) do
        for _, dep in ipairs(task.deps or {}) do
            if dep == completedTaskId then
                table.insert(dependents, task.id)
                break
            end
        end
    end
    return dependents
end

-- Start data transfers from completed task to its dependent tasks
function StartDataTransfers(completedTaskId)
    local sourceNode = ConfiguredDagState.taskNodeAssignment[completedTaskId]
    if sourceNode == nil then return end

    local dependents = FindDependentTasks(completedTaskId)
    local transfersStarted = 0

    for _, depTaskId in ipairs(dependents) do
        if not ConfiguredDagState.completedTasks[depTaskId] then
            local targetNode = ConfiguredDagState.taskNodeAssignment[depTaskId]

            if targetNode ~= nil and targetNode ~= sourceNode then
                print("IoBT DAG: Transferring data " .. completedTaskId .. " -> " .. depTaskId ..
                      " (C" .. sourceNode .. " -> C" .. targetNode .. ")")
                Blue.AddTaskTransferWithNodes(completedTaskId, depTaskId, sourceNode, targetNode, "data")
                transfersStarted = transfersStarted + 1

                if not ConfiguredDagState.pendingTransfers[depTaskId] then
                    ConfiguredDagState.pendingTransfers[depTaskId] = {}
                end
                table.insert(ConfiguredDagState.pendingTransfers[depTaskId], completedTaskId)
            end
        end
    end

    if transfersStarted > 0 then
        Trigger.AfterDelay(ConfiguredDagState.transferDuration, function()
            Blue.ClearActiveLinks()
            ExecuteNextDagTasks()
        end)
    else
        ExecuteNextDagTasks()
    end
end

-- Mark a task as complete and trigger dependent tasks
function CompleteTask(taskId)
    if ConfiguredDagState.completedTasks[taskId] then
        return
    end

    print("IoBT DAG: " .. taskId .. " complete")
    Blue.CompleteTask(taskId)
    ConfiguredDagState.completedTasks[taskId] = true
    ConfiguredDagState.runningTasks[taskId] = nil

    local allDone = true
    for _, task in ipairs(IoBTConfig.dagTasks) do
        if not ConfiguredDagState.completedTasks[task.id] then
            allDone = false
            break
        end
    end

    if allDone then
        print("IoBT DAG: All tasks complete! Restarting in 3 seconds...")
        Blue.ClearActiveLinks()
        Trigger.AfterDelay(75, function()
            RestartDag()
        end)
    else
        StartDataTransfers(taskId)
    end
end

-- Restart the DAG execution
function RestartDag()
    print("IoBT DAG: Restarting DAG...")
    Blue.ClearDag()
    Blue.ClearActiveLinks()
    ConfiguredDagState.started = false
    ConfiguredDagState.completedTasks = {}
    ConfiguredDagState.runningTasks = {}
    ConfiguredDagState.stalledTasks = {}
    ConfiguredDagState.taskNodeAssignment = {}
    ConfiguredDagState.pendingTransfers = {}
    ConfiguredDagState.sagaScheduleRequested = false
    ConfiguredDagState.sagaScheduleReceived = false
    ConfiguredDagState.sagaMonitorCount = 0
    Blue.ClearPendingSchedule()

    Trigger.AfterDelay(25, function()
        InitConfiguredDag()
    end)
end

-- ============================================
-- World Initialization
-- ============================================

-- Called once when the map loads
function WorldLoaded()
    -- Get the Blue player
    Blue = Player.GetPlayer("Blue")

    if not Blue then
        print("ERROR: Blue player not found!")
        return
    end

    print("IoBT: Initializing simulation...")
    print("IoBT: Export enabled = " .. tostring(IoBTConfig.export.enabled))
    print("IoBT: Sample interval = " .. IoBTConfig.export.sampleInterval .. " ticks")
    print("IoBT: Stop after = " .. IoBTConfig.export.stopAfterTicks .. " ticks")

    -- Spawn buildings
    for _, bldg in ipairs(IoBTConfig.buildings) do
        local owner = Player.GetPlayer(bldg.owner)
        if owner then
            local actor = Actor.Create(bldg.type, true, {
                Owner = owner,
                Location = CPos.New(bldg.x, bldg.y)
            })
            IoBTState.buildings[bldg.id] = {
                actor = actor,
                config = bldg
            }
            print("IoBT: Spawned building " .. bldg.id .. " (" .. bldg.type .. ") at " .. bldg.x .. "," .. bldg.y)
        else
            print("ERROR: Owner not found for building " .. bldg.id)
        end
    end

    IoBTState.initialized = true
    print("IoBT: Initialization complete. " .. #IoBTConfig.units .. " units, " .. #IoBTConfig.buildings .. " buildings configured.")

    -- Start DAG after units have spawned
    Trigger.AfterDelay(50, function()
        if IoBTConfig.dagTasks and #IoBTConfig.dagTasks > 0 then
            print("IoBT: Using DAG from iobt-config.lua (" .. #IoBTConfig.dagTasks .. " tasks)")
            InitConfiguredDag()
        else
            print("IoBT: No DAG tasks configured")
        end
    end)
end

-- Called every game tick
function Tick()
    if not IoBTState.initialized then
        return
    end

    local currentTime = DateTime.GameTime

    -- Process each configured unit
    for _, unitDef in ipairs(IoBTConfig.units) do
        local targetPos = GetInterpolatedPosition(unitDef.waypoints, currentTime)
        local state = IoBTState.units[unitDef.id]

        if targetPos then
            if not state or not state.actor or state.actor.IsDead then
                local owner = Player.GetPlayer(unitDef.owner)
                if owner then
                    local actor = Actor.Create(unitDef.type, true, {
                        Owner = owner,
                        Location = targetPos
                    })
                    state = {
                        actor = actor,
                        lastTargetPos = targetPos,
                        config = unitDef
                    }
                    IoBTState.units[unitDef.id] = state
                    print("IoBT: Spawned unit " .. unitDef.id .. " (" .. unitDef.type .. ") at tick " .. currentTime)
                end
            elseif state.lastTargetPos.X ~= targetPos.X or state.lastTargetPos.Y ~= targetPos.Y then
                state.actor.Stop()
                state.actor.Move(targetPos)
                state.lastTargetPos = targetPos
            end
        end
    end

    -- Position recording at configured interval
    if IoBTConfig.export.enabled then
        if currentTime % IoBTConfig.export.sampleInterval == 0 then
            RecordPositions(currentTime)
        end

        if IoBTConfig.export.stopAfterTicks > 0 and currentTime >= IoBTConfig.export.stopAfterTicks then
            ExportLog()
            IoBTConfig.export.enabled = false
            print("IoBT: Simulation recording complete.")
        end
    end
end
