--[[
   IoBT Configuration
   Generated by IoBT-Viz Config GUI
   Date: 2026-01-24 16:56:02

   Nodes: 50 (70% infantry, 30% vehicles)
   Communication Range: 8 cells
   DAG: 3 levels, 2 branches (15 tasks)
   Task Duration: 75 ticks per task
   Transfer Duration: 80 ticks (cyan link highlight)
   Simulation: 60 seconds
]]
IoBTConfig = {
    ticksPerSecond = 25,

    export = {
        enabled = true,
        sampleInterval = 125,  -- Every 5 seconds
        stopAfterTicks = 1500,  -- 60 seconds
    },

    networkSettings = {
        range = 8,
        maxDataRate = 100,
        minDataRate = 10,
    },

    units = {},

    buildings = {
        -- Power plants to avoid low power warning
        { id = "power1", type = "powr", owner = "Blue", x = 74, y = 76 },
        { id = "power2", type = "powr", owner = "Blue", x = 54, y = 76 },
        -- Command bases
        { id = "hq1", type = "dome", owner = "Blue", x = 74, y = 74 },
        { id = "hq2", type = "dome", owner = "Blue", x = 54, y = 74 },
        { id = "base1", type = "fact", owner = "Blue", x = 74, y = 70 },
        { id = "base2", type = "fact", owner = "Blue", x = 54, y = 70 },
    },

    networkLinks = {},

    dagTasks = {
        { id = "T0", name = "Task 0", deps = {} },
        { id = "T1", name = "Task 1", deps = {"T0"} },
        { id = "T2", name = "Task 2", deps = {"T1"} },
        { id = "T3", name = "Task 3", deps = {"T2"} },
        { id = "T4", name = "Task 4", deps = {"T2"} },
        { id = "T5", name = "Task 5", deps = {"T1"} },
        { id = "T6", name = "Task 6", deps = {"T5"} },
        { id = "T7", name = "Task 7", deps = {"T5"} },
        { id = "T8", name = "Task 8", deps = {"T0"} },
        { id = "T9", name = "Task 9", deps = {"T8"} },
        { id = "T10", name = "Task 10", deps = {"T9"} },
        { id = "T11", name = "Task 11", deps = {"T9"} },
        { id = "T12", name = "Task 12", deps = {"T8"} },
        { id = "T13", name = "Task 13", deps = {"T12"} },
        { id = "T14", name = "Task 14", deps = {"T12"} },
    }
}
-- Helper to add infantry squad (rifle soldiers only - e1)
local function addInfantrySquad(squadId, squadSize, startX, startY, waypoints)
    for i = 1, squadSize do
        local offsetX = (i % 5) - 2  -- Spread in a 5-wide formation
        local offsetY = math.floor(i / 5)
        local unit = {
            id = "inf_" .. squadId .. "_" .. i,
            type = "e1",  -- Rifle infantry only
            owner = "Blue",
            waypoints = {}
        }
        for _, wp in ipairs(waypoints) do
            table.insert(unit.waypoints, {
                time = wp.time + (i * 2),  -- Slight time offset per soldier
                x = math.max(51, math.min(77, wp.x + offsetX)),
                y = math.max(49, math.min(78, wp.y + offsetY))
            })
        end
        table.insert(IoBTConfig.units, unit)
    end
end

-- Helper to add vehicle group
local function addVehicleGroup(groupId, groupSize, unitType, waypoints)
    for i = 1, groupSize do
        local offsetX = (i % 3) - 1  -- Spread in a 3-wide formation
        local offsetY = math.floor(i / 3) * 2
        local unit = {
            id = "veh_" .. groupId .. "_" .. i,
            type = unitType,
            owner = "Blue",
            waypoints = {}
        }
        for _, wp in ipairs(waypoints) do
            table.insert(unit.waypoints, {
                time = wp.time + (i * 5),  -- Slight time offset per vehicle
                x = math.max(51, math.min(77, wp.x + offsetX)),
                y = math.max(49, math.min(78, wp.y + offsetY))
            })
        end
        table.insert(IoBTConfig.units, unit)
    end
end

-- INFANTRY SQUADS

-- Squad 1: 7 infantry
addInfantrySquad(1, 7, 76, 63, {
    { time = 0, x = 76, y = 63 },
    { time = 337, x = 71, y = 63 },
    { time = 675, x = 67, y = 63 },
    { time = 1012, x = 62, y = 63 },
    { time = 1350, x = 58, y = 64 }
})

-- Squad 2: 7 infantry
addInfantrySquad(2, 7, 67, 75, {
    { time = 50, x = 67, y = 75 },
    { time = 387, x = 66, y = 70 },
    { time = 725, x = 65, y = 65 },
    { time = 1062, x = 64, y = 60 },
    { time = 1400, x = 63, y = 56 }
})

-- Squad 3: 7 infantry
addInfantrySquad(3, 7, 54, 70, {
    { time = 100, x = 54, y = 70 },
    { time = 437, x = 57, y = 66 },
    { time = 775, x = 60, y = 63 },
    { time = 1112, x = 63, y = 60 },
    { time = 1450, x = 67, y = 57 }
})

-- Squad 4: 7 infantry
addInfantrySquad(4, 7, 54, 55, {
    { time = 150, x = 54, y = 55 },
    { time = 487, x = 57, y = 58 },
    { time = 825, x = 60, y = 61 },
    { time = 1162, x = 63, y = 64 },
    { time = 1500, x = 67, y = 68 }
})

-- Squad 5: 7 infantry
addInfantrySquad(5, 7, 67, 50, {
    { time = 200, x = 67, y = 50 },
    { time = 537, x = 66, y = 54 },
    { time = 875, x = 65, y = 59 },
    { time = 1212, x = 64, y = 64 },
    { time = 1550, x = 63, y = 69 }
})

-- VEHICLE GROUPS

-- Group 1: 3 jeep
addVehicleGroup(1, 3, "jeep", {
    { time = 25, x = 77, y = 65 },
    { time = 343, x = 72, y = 64 },
    { time = 662, x = 67, y = 64 },
    { time = 981, x = 62, y = 63 },
    { time = 1300, x = 57, y = 63 }
})

-- Group 2: 3 apc
addVehicleGroup(2, 3, "apc", {
    { time = 75, x = 69, y = 77 },
    { time = 393, x = 67, y = 71 },
    { time = 712, x = 65, y = 66 },
    { time = 1031, x = 63, y = 60 },
    { time = 1350, x = 62, y = 55 }
})

-- Group 3: 3 1tnk
addVehicleGroup(3, 3, "1tnk", {
    { time = 125, x = 56, y = 72 },
    { time = 443, x = 58, y = 68 },
    { time = 762, x = 61, y = 64 },
    { time = 1081, x = 63, y = 60 },
    { time = 1400, x = 66, y = 56 }
})

-- Group 4: 3 2tnk
addVehicleGroup(4, 3, "2tnk", {
    { time = 175, x = 56, y = 57 },
    { time = 493, x = 58, y = 59 },
    { time = 812, x = 61, y = 62 },
    { time = 1131, x = 63, y = 64 },
    { time = 1450, x = 66, y = 67 }
})

-- Group 5: 3 3tnk
addVehicleGroup(5, 3, "3tnk", {
    { time = 225, x = 69, y = 52 },
    { time = 543, x = 67, y = 56 },
    { time = 862, x = 65, y = 60 },
    { time = 1181, x = 63, y = 64 },
    { time = 1500, x = 62, y = 68 }
})

-- ============================================
-- DAG Execution Logic (Generated)
-- Network-Aware Scheduling with Connectivity Checks
-- ============================================

-- Track DAG execution state
ConfiguredDagState = {
    started = false,
    taskIndex = 1,
    tasks = {},
    completedTasks = {},
    runningTasks = {},      -- taskId -> true for currently running
    stalledTasks = {},      -- taskId -> true for connectivity-blocked
    taskNodeAssignment = {}, -- taskId -> nodeIndex that ran/is running the task
    pendingTransfers = {},  -- taskId -> list of pending incoming transfers
    transferDuration = 80  -- ticks for data transfer visualization
}

-- Initialize the configured DAG
function InitConfiguredDag()
    if ConfiguredDagState.started then return end

    local nodeCount = Blue.GetComputeNodeCount()
    print("IoBT DAG: Found " .. nodeCount .. " compute nodes")

    if nodeCount < 1 then
        print("IoBT DAG: Need at least 1 compute node")
        return
    end

    ConfiguredDagState.started = true
    ConfiguredDagState.completedTasks = {}
    ConfiguredDagState.runningTasks = {}
    ConfiguredDagState.stalledTasks = {}
    ConfiguredDagState.taskNodeAssignment = {}
    ConfiguredDagState.pendingTransfers = {}
    print("IoBT DAG: Starting configured DAG execution...")

    -- Register all tasks with the DAG system
    Blue.AddDagTask("T0", "Task 0", "")
    Blue.AddDagTask("T1", "Task 1", "T0")
    Blue.AddDagTask("T2", "Task 2", "T1")
    Blue.AddDagTask("T3", "Task 3", "T2")
    Blue.AddDagTask("T4", "Task 4", "T2")
    Blue.AddDagTask("T5", "Task 5", "T1")
    Blue.AddDagTask("T6", "Task 6", "T5")
    Blue.AddDagTask("T7", "Task 7", "T5")
    Blue.AddDagTask("T8", "Task 8", "T0")
    Blue.AddDagTask("T9", "Task 9", "T8")
    Blue.AddDagTask("T10", "Task 10", "T9")
    Blue.AddDagTask("T11", "Task 11", "T9")
    Blue.AddDagTask("T12", "Task 12", "T8")
    Blue.AddDagTask("T13", "Task 13", "T12")
    Blue.AddDagTask("T14", "Task 14", "T12")

    -- Start executing tasks
    ExecuteNextDagTasks()

    -- Start periodic connectivity check for stalled tasks
    StartConnectivityMonitor()
end

-- Check if a task's dependencies are satisfied (all completed)
function AreDependenciesSatisfied(taskId)
    for _, task in ipairs(IoBTConfig.dagTasks) do
        if task.id == taskId then
            for _, dep in ipairs(task.deps) do
                if not ConfiguredDagState.completedTasks[dep] then
                    return false
                end
            end
            return true
        end
    end
    return true
end

-- Check if all parent task nodes are connected to the target node
-- Returns true if task can be assigned to targetNode, false if blocked by connectivity
function CanAssignToNode(taskId, targetNode)
    for _, task in ipairs(IoBTConfig.dagTasks) do
        if task.id == taskId then
            for _, dep in ipairs(task.deps) do
                local parentNode = ConfiguredDagState.taskNodeAssignment[dep]
                if parentNode ~= nil then
                    -- Check if parent node is connected to target node
                    if not Blue.AreNodesConnected(parentNode, targetNode) then
                        return false, dep, parentNode
                    end
                end
            end
            return true, nil, nil
        end
    end
    return true, nil, nil
end

-- Pre-assign nodes to tasks (for transfer visualization) without starting them
function PreAssignTaskNodes()
    local nodeCount = Blue.GetComputeNodeCount()
    local nodeIndex = 0

    for _, task in ipairs(IoBTConfig.dagTasks) do
        local taskId = task.id
        -- Only pre-assign if not already assigned
        if ConfiguredDagState.taskNodeAssignment[taskId] == nil then
            local assignedNode = nodeIndex % nodeCount
            nodeIndex = nodeIndex + 1
            ConfiguredDagState.taskNodeAssignment[taskId] = assignedNode
        end
    end
end

-- Find and execute tasks that are ready (dependencies satisfied + connectivity OK)
function ExecuteNextDagTasks()
    local nodeCount = Blue.GetComputeNodeCount()

    -- First, pre-assign all tasks so we know where they'll run
    PreAssignTaskNodes()

    for _, task in ipairs(IoBTConfig.dagTasks) do
        local taskId = task.id

        -- Skip completed, running, or stalled tasks (Lua 5.1 compatible - no goto)
        local shouldSkip = ConfiguredDagState.completedTasks[taskId] or
                          ConfiguredDagState.runningTasks[taskId] or
                          ConfiguredDagState.stalledTasks[taskId]

        if not shouldSkip then
            -- Check if dependencies are satisfied
            if AreDependenciesSatisfied(taskId) then
                -- Get pre-assigned node
                local assignedNode = ConfiguredDagState.taskNodeAssignment[taskId]

                -- Check connectivity to parent task nodes
                local canAssign, blockedBy, blockedNode = CanAssignToNode(taskId, assignedNode)

                if canAssign then
                    -- Assign and run the task
                    print("IoBT DAG: Assigning " .. taskId .. " to node C" .. assignedNode)
                    Blue.AssignTask(taskId, assignedNode)
                    ConfiguredDagState.runningTasks[taskId] = true

                    -- Schedule completion after task duration
                    local taskDuration = 75  -- ticks per task
                    Trigger.AfterDelay(taskDuration, function()
                        CompleteTask(taskId)
                    end)
                else
                    -- Stall the task - waiting for connectivity
                    print("IoBT DAG: Task " .. taskId .. " stalled - C" .. assignedNode ..
                          " disconnected from parent " .. blockedBy .. " (C" .. blockedNode .. ")")
                    Blue.StallTask(taskId)
                    ConfiguredDagState.stalledTasks[taskId] = true
                end
            end
        end
    end
end

-- Periodically check if stalled tasks can resume
function StartConnectivityMonitor()
    Trigger.AfterDelay(25, function()
        if not ConfiguredDagState.started then return end

        local anyUnstalled = false

        for taskId, _ in pairs(ConfiguredDagState.stalledTasks) do
            local targetNode = ConfiguredDagState.taskNodeAssignment[taskId]
            if targetNode then
                local canAssign, _, _ = CanAssignToNode(taskId, targetNode)
                if canAssign then
                    -- Connectivity restored - unstall and run
                    print("IoBT DAG: Task " .. taskId .. " connectivity restored, resuming on C" .. targetNode)
                    Blue.UnstallTask(taskId)
                    ConfiguredDagState.stalledTasks[taskId] = nil

                    Blue.AssignTask(taskId, targetNode)
                    ConfiguredDagState.runningTasks[taskId] = true

                    local taskDuration = 75
                    Trigger.AfterDelay(taskDuration, function()
                        CompleteTask(taskId)
                    end)

                    anyUnstalled = true
                end
            end
        end

        -- Continue monitoring
        StartConnectivityMonitor()
    end)
end

-- Find all tasks that depend on the given task
function FindDependentTasks(completedTaskId)
    local dependents = {}
    for _, task in ipairs(IoBTConfig.dagTasks) do
        for _, dep in ipairs(task.deps) do
            if dep == completedTaskId then
                table.insert(dependents, task.id)
                break
            end
        end
    end
    return dependents
end

-- Start data transfers from completed task to its dependent tasks
function StartDataTransfers(completedTaskId)
    local sourceNode = ConfiguredDagState.taskNodeAssignment[completedTaskId]
    if sourceNode == nil then return end

    local dependents = FindDependentTasks(completedTaskId)
    local transfersStarted = 0

    for _, depTaskId in ipairs(dependents) do
        -- Only transfer if dependent task hasn't completed yet
        if not ConfiguredDagState.completedTasks[depTaskId] then
            -- Get the target node - assign if not yet assigned
            local targetNode = ConfiguredDagState.taskNodeAssignment[depTaskId]

            -- Only show transfer if tasks are on different nodes
            if targetNode ~= nil and targetNode ~= sourceNode then
                print("IoBT DAG: Transferring data " .. completedTaskId .. " -> " .. depTaskId ..
                      " (C" .. sourceNode .. " -> C" .. targetNode .. ")")
                -- Use AddTaskTransferWithNodes to pass explicit node indices
                -- (dest task may not be "assigned" in C# yet, only pre-assigned in Lua)
                Blue.AddTaskTransferWithNodes(completedTaskId, depTaskId, sourceNode, targetNode, "data")
                transfersStarted = transfersStarted + 1

                -- Track pending transfer for the dependent task
                if not ConfiguredDagState.pendingTransfers[depTaskId] then
                    ConfiguredDagState.pendingTransfers[depTaskId] = {}
                end
                table.insert(ConfiguredDagState.pendingTransfers[depTaskId], completedTaskId)
            end
        end
    end

    -- Schedule transfer completion and link cleanup
    if transfersStarted > 0 then
        Trigger.AfterDelay(ConfiguredDagState.transferDuration, function()
            Blue.ClearActiveLinks()
            -- Now execute any newly unblocked tasks
            ExecuteNextDagTasks()
        end)
    else
        -- No transfers needed, execute immediately
        ExecuteNextDagTasks()
    end
end

-- Mark a task as complete and trigger dependent tasks
function CompleteTask(taskId)
    if ConfiguredDagState.completedTasks[taskId] then
        return  -- Already completed
    end

    print("IoBT DAG: " .. taskId .. " complete")
    Blue.CompleteTask(taskId)
    ConfiguredDagState.completedTasks[taskId] = true
    ConfiguredDagState.runningTasks[taskId] = nil

    -- Check if all tasks are done
    local allDone = true
    for _, task in ipairs(IoBTConfig.dagTasks) do
        if not ConfiguredDagState.completedTasks[task.id] then
            allDone = false
            break
        end
    end

    if allDone then
        print("IoBT DAG: All tasks complete! Restarting in 3 seconds...")
        Blue.ClearActiveLinks()
        Trigger.AfterDelay(75, function()
            RestartDag()
        end)
    else
        -- Start data transfers to dependent tasks
        StartDataTransfers(taskId)
    end
end

-- Restart the DAG execution
function RestartDag()
    print("IoBT DAG: Restarting DAG...")
    Blue.ClearDag()
    Blue.ClearActiveLinks()
    ConfiguredDagState.started = false
    ConfiguredDagState.completedTasks = {}
    ConfiguredDagState.runningTasks = {}
    ConfiguredDagState.stalledTasks = {}
    ConfiguredDagState.taskNodeAssignment = {}
    ConfiguredDagState.pendingTransfers = {}

    Trigger.AfterDelay(25, function()
        InitConfiguredDag()
    end)
end

-- Flag to use configured DAG instead of hardcoded demo
UseConfiguredDag = true
