--[[
   IoBT Configuration (DATA ONLY)
   Generated by IoBT-Viz Config GUI
   Date: 2026-01-24 22:09:45

   Nodes: 15 (70% infantry, 30% vehicles)
   Communication Range: 8 cells
   DAG: 1 levels, 8 branches (9 tasks)
   Task Duration: 75 ticks per task
   Transfer Duration: 80 ticks (cyan link highlight)
   Simulation: 60 seconds

   NOTE: Execution logic is in iobt-main.lua (not here).
   This file defines data only: units, buildings, dagTasks, network settings.
]]
IoBTConfig = {
    ticksPerSecond = 25,

    export = {
        enabled = true,
        sampleInterval = 125,  -- Every 5 seconds
        stopAfterTicks = 1500,  -- 60 seconds
    },

    networkSettings = {
        range = 8,
        maxDataRate = 100,
        minDataRate = 10,
    },

    dagSettings = {
        taskDuration = 75,  -- ticks per task
        transferDuration = 80,  -- ticks for transfer visualization
    },

    units = {},

    buildings = {
        -- Power plants to avoid low power warning
        { id = "power1", type = "powr", owner = "Blue", x = 74, y = 76 },
        { id = "power2", type = "powr", owner = "Blue", x = 54, y = 76 },
        -- Command bases
        { id = "hq1", type = "dome", owner = "Blue", x = 74, y = 74 },
        { id = "hq2", type = "dome", owner = "Blue", x = 54, y = 74 },
        { id = "base1", type = "fact", owner = "Blue", x = 74, y = 70 },
        { id = "base2", type = "fact", owner = "Blue", x = 54, y = 70 },
    },

    networkLinks = {},

    dagTasks = {
        { id = "T0", name = "Task 0", deps = {} },
        { id = "T1", name = "Task 1", deps = {"T0"} },
        { id = "T2", name = "Task 2", deps = {"T0"} },
        { id = "T3", name = "Task 3", deps = {"T0"} },
        { id = "T4", name = "Task 4", deps = {"T0"} },
        { id = "T5", name = "Task 5", deps = {"T0"} },
        { id = "T6", name = "Task 6", deps = {"T0"} },
        { id = "T7", name = "Task 7", deps = {"T0"} },
        { id = "T8", name = "Task 8", deps = {"T0"} },
    }
}
-- Helper to add infantry squad (rifle soldiers only - e1)
local function addInfantrySquad(squadId, squadSize, startX, startY, waypoints)
    for i = 1, squadSize do
        local offsetX = (i % 5) - 2  -- Spread in a 5-wide formation
        local offsetY = math.floor(i / 5)
        local unit = {
            id = "inf_" .. squadId .. "_" .. i,
            type = "e1",  -- Rifle infantry only
            owner = "Blue",
            waypoints = {}
        }
        for _, wp in ipairs(waypoints) do
            table.insert(unit.waypoints, {
                time = wp.time + (i * 2),  -- Slight time offset per soldier
                x = math.max(51, math.min(77, wp.x + offsetX)),
                y = math.max(49, math.min(78, wp.y + offsetY))
            })
        end
        table.insert(IoBTConfig.units, unit)
    end
end

-- Helper to add vehicle group
local function addVehicleGroup(groupId, groupSize, unitType, waypoints)
    for i = 1, groupSize do
        local offsetX = (i % 3) - 1  -- Spread in a 3-wide formation
        local offsetY = math.floor(i / 3) * 2
        local unit = {
            id = "veh_" .. groupId .. "_" .. i,
            type = unitType,
            owner = "Blue",
            waypoints = {}
        }
        for _, wp in ipairs(waypoints) do
            table.insert(unit.waypoints, {
                time = wp.time + (i * 5),  -- Slight time offset per vehicle
                x = math.max(51, math.min(77, wp.x + offsetX)),
                y = math.max(49, math.min(78, wp.y + offsetY))
            })
        end
        table.insert(IoBTConfig.units, unit)
    end
end

-- INFANTRY SQUADS

-- Squad 1: 2 infantry
addInfantrySquad(1, 2, 76, 63, {
    { time = 0, x = 76, y = 63 },
    { time = 337, x = 71, y = 63 },
    { time = 675, x = 67, y = 63 },
    { time = 1012, x = 62, y = 63 },
    { time = 1350, x = 58, y = 64 }
})

-- Squad 2: 2 infantry
addInfantrySquad(2, 2, 67, 75, {
    { time = 50, x = 67, y = 75 },
    { time = 387, x = 66, y = 70 },
    { time = 725, x = 65, y = 65 },
    { time = 1062, x = 64, y = 60 },
    { time = 1400, x = 63, y = 56 }
})

-- Squad 3: 2 infantry
addInfantrySquad(3, 2, 54, 70, {
    { time = 100, x = 54, y = 70 },
    { time = 437, x = 57, y = 66 },
    { time = 775, x = 60, y = 63 },
    { time = 1112, x = 63, y = 60 },
    { time = 1450, x = 67, y = 57 }
})

-- Squad 4: 2 infantry
addInfantrySquad(4, 2, 54, 55, {
    { time = 150, x = 54, y = 55 },
    { time = 487, x = 57, y = 58 },
    { time = 825, x = 60, y = 61 },
    { time = 1162, x = 63, y = 64 },
    { time = 1500, x = 67, y = 68 }
})

-- Squad 5: 2 infantry
addInfantrySquad(5, 2, 67, 50, {
    { time = 200, x = 67, y = 50 },
    { time = 537, x = 66, y = 54 },
    { time = 875, x = 65, y = 59 },
    { time = 1212, x = 64, y = 64 },
    { time = 1550, x = 63, y = 69 }
})

-- VEHICLE GROUPS

-- Group 1: 2 jeep
addVehicleGroup(1, 2, "jeep", {
    { time = 25, x = 77, y = 65 },
    { time = 343, x = 72, y = 64 },
    { time = 662, x = 67, y = 64 },
    { time = 981, x = 62, y = 63 },
    { time = 1300, x = 57, y = 63 }
})

-- Group 2: 2 apc
addVehicleGroup(2, 2, "apc", {
    { time = 75, x = 69, y = 77 },
    { time = 393, x = 67, y = 71 },
    { time = 712, x = 65, y = 66 },
    { time = 1031, x = 63, y = 60 },
    { time = 1350, x = 62, y = 55 }
})

-- Group 3: 2 1tnk
addVehicleGroup(3, 2, "1tnk", {
    { time = 125, x = 56, y = 72 },
    { time = 443, x = 58, y = 68 },
    { time = 762, x = 61, y = 64 },
    { time = 1081, x = 63, y = 60 },
    { time = 1400, x = 66, y = 56 }
})

-- Group 4: 2 2tnk
addVehicleGroup(4, 2, "2tnk", {
    { time = 175, x = 56, y = 57 },
    { time = 493, x = 58, y = 59 },
    { time = 812, x = 61, y = 62 },
    { time = 1131, x = 63, y = 64 },
    { time = 1450, x = 66, y = 67 }
})

-- Group 5: 1 3tnk
addVehicleGroup(5, 1, "3tnk", {
    { time = 225, x = 69, y = 52 },
    { time = 543, x = 67, y = 56 },
    { time = 862, x = 65, y = 60 },
    { time = 1181, x = 63, y = 64 },
    { time = 1500, x = 62, y = 68 }
})
