--[[
   IoBT Main Visualization Script

   This script implements:
   - Time-waypoint interpolation for unit movement
   - Building placement
   - Position recording and export
   - DAG execution with SAGA scheduler integration
   - Network-aware task scheduling

   The DAG structure is defined in iobt-config.lua (generated by config GUI).
   This file contains all execution logic and SAGA integration.
]]

-- State tracking
IoBTState = {
    units = {},
    buildings = {},
    initialized = false
}

-- Position log for export
PositionLog = {}

-- ============================================
-- Run Logging System (console-based - io library not available in OpenRA sandbox)
-- ============================================
RunLog = {
    startTick = 0,
    lastStateSnapshot = -1000  -- Force first snapshot
}

function InitRunLog()
    print("=== IoBT Run Log ===")
    print("================================================================================")
end

function Log(category, message)
    local tick = DateTime.GameTime or 0
    local elapsed = tick - RunLog.startTick
    print(string.format("[%05d] %-10s %s", elapsed, category, message))
end

function LogSection(title)
    print("")
    print("--- " .. title .. " ---")
end

function LogDagState()
    local tick = DateTime.GameTime or 0

    -- Count tasks by state
    local completed, running, stalled, pending = 0, 0, 0, 0
    local completedList, runningList, stalledList = {}, {}, {}

    for _, task in ipairs(IoBTConfig.dagTasks) do
        local id = task.id
        local node = ConfiguredDagState.taskNodeAssignment[id]
        local nodeStr = node and ("C" .. node) or "?"

        if ConfiguredDagState.completedTasks[id] then
            completed = completed + 1
            table.insert(completedList, id .. "@" .. nodeStr)
        elseif ConfiguredDagState.runningTasks[id] then
            running = running + 1
            table.insert(runningList, id .. "@" .. nodeStr)
        elseif ConfiguredDagState.stalledTasks[id] then
            stalled = stalled + 1
            table.insert(stalledList, id .. "@" .. nodeStr)
        else
            pending = pending + 1
        end
    end

    Log("DAG-STATE", string.format("Completed:%d Running:%d Stalled:%d Pending:%d",
        completed, running, stalled, pending))
    if #completedList > 0 then
        Log("DAG-STATE", "  Completed: " .. table.concat(completedList, ", "))
    end
    if #runningList > 0 then
        Log("DAG-STATE", "  Running: " .. table.concat(runningList, ", "))
    end
    if #stalledList > 0 then
        Log("DAG-STATE", "  STALLED: " .. table.concat(stalledList, ", "))
    end
end

function LogNetworkState()
    local nodeCount = Blue.GetComputeNodeCount()

    -- Build connectivity summary - count connections per node
    local connCounts = {}
    local totalConnections = 0
    for i = 0, nodeCount - 1 do
        local count = 0
        for j = 0, nodeCount - 1 do
            if i ~= j and Blue.AreNodesConnected(i, j) then
                count = count + 1
            end
        end
        connCounts[i] = count
        totalConnections = totalConnections + count
    end

    -- Find isolated nodes (0 connections) and well-connected nodes
    local isolated, sparse = {}, {}
    for i = 0, nodeCount - 1 do
        if connCounts[i] == 0 then
            table.insert(isolated, "C" .. i)
        elseif connCounts[i] <= 2 then
            table.insert(sparse, "C" .. i .. "(" .. connCounts[i] .. ")")
        end
    end

    Log("NETWORK", string.format("Nodes:%d TotalLinks:%d", nodeCount, totalConnections / 2))
    if #isolated > 0 then
        Log("NETWORK", "  Isolated: " .. table.concat(isolated, ", "))
    end
    if #sparse > 0 then
        Log("NETWORK", "  Sparse: " .. table.concat(sparse, ", "))
    end
end

function LogStateSnapshot(reason)
    LogSection("STATE SNAPSHOT: " .. reason)
    LogNetworkState()
    LogDagState()
end

function MaybeLogPeriodicSnapshot()
    local tick = DateTime.GameTime or 0
    -- Snapshot every 250 ticks (10 seconds at 25 tps)
    if tick - RunLog.lastStateSnapshot >= 250 then
        RunLog.lastStateSnapshot = tick
        LogStateSnapshot("Periodic")
    end
end

function CloseRunLog()
    LogSection("RUN COMPLETE")
end

-- Linear interpolation helper
function Lerp(a, b, t)
    return a + (b - a) * t
end

-- Get interpolated target position for a unit at current game time
-- Returns nil if the unit shouldn't exist yet (before first waypoint)
function GetInterpolatedPosition(waypoints, currentTime)
    -- Not yet at first waypoint
    if currentTime < waypoints[1].time then
        return nil
    end

    -- Find the waypoint segment we're in
    for i = 1, #waypoints - 1 do
        local wp1 = waypoints[i]
        local wp2 = waypoints[i + 1]

        if currentTime >= wp1.time and currentTime < wp2.time then
            -- Interpolate between waypoints
            local duration = wp2.time - wp1.time
            local elapsed = currentTime - wp1.time
            local t = elapsed / duration

            local x = math.floor(Lerp(wp1.x, wp2.x, t) + 0.5)
            local y = math.floor(Lerp(wp1.y, wp2.y, t) + 0.5)

            return CPos.New(x, y)
        end
    end

    -- Past the last waypoint - stay at final position
    local lastWp = waypoints[#waypoints]
    return CPos.New(lastWp.x, lastWp.y)
end

-- Record current positions of all tracked units
function RecordPositions(currentTime)
    for id, state in pairs(IoBTState.units) do
        if state.actor and not state.actor.IsDead then
            local pos = state.actor.Location
            table.insert(PositionLog, {
                time = currentTime,
                unit = id,
                x = pos.X,
                y = pos.Y
            })
        end
    end
end

-- Export recorded positions as CSV to console
function ExportLog()
    print("=== IOBT POSITION LOG START ===")
    print("time,unit,x,y")
    for _, entry in ipairs(PositionLog) do
        print(entry.time .. "," .. entry.unit .. "," .. entry.x .. "," .. entry.y)
    end
    print("=== IOBT POSITION LOG END ===")
    print("Total entries: " .. #PositionLog)
end

-- ============================================
-- DAG Execution Logic with SAGA Integration
-- ============================================

-- Track DAG execution state
-- Note: transferDuration and taskDuration can be overridden by IoBTConfig.dagSettings
ConfiguredDagState = {
    started = false,
    completedTasks = {},
    runningTasks = {},      -- taskId -> true for currently running
    stalledTasks = {},      -- taskId -> true for connectivity-blocked
    taskNodeAssignment = {}, -- taskId -> nodeIndex that ran/is running the task
    pendingTransfers = {},  -- taskId -> list of pending incoming transfers
    transferDuration = 50,  -- default: ticks for data transfer visualization
    taskDuration = 75,      -- default: ticks per task
    -- SAGA scheduling state
    sagaScheduleRequested = false,
    sagaScheduleReceived = false,
    sagaMonitorCount = 0,
    useSagaScheduler = true,  -- Set to false to force round-robin
    currentPartition = nil    -- Set when in H-mode to restrict scheduling
}

-- Apply settings from IoBTConfig.dagSettings if available
function ApplyDagSettings()
    if IoBTConfig and IoBTConfig.dagSettings then
        if IoBTConfig.dagSettings.taskDuration then
            ConfiguredDagState.taskDuration = IoBTConfig.dagSettings.taskDuration
        end
        if IoBTConfig.dagSettings.transferDuration then
            ConfiguredDagState.transferDuration = IoBTConfig.dagSettings.transferDuration
        end
        print("IoBT DAG: Using config settings - taskDuration=" .. ConfiguredDagState.taskDuration ..
              ", transferDuration=" .. ConfiguredDagState.transferDuration)
    end
end

-- Apply network settings from IoBTConfig.networkSettings if available
function ApplyNetworkSettings()
    if IoBTConfig and IoBTConfig.networkSettings then
        if IoBTConfig.networkSettings.range then
            Blue.SetNetworkRadius(IoBTConfig.networkSettings.range)
            print("IoBT Network: Set communication range to " .. IoBTConfig.networkSettings.range)
        end
    end
end

-- Wait until enough compute nodes are available before starting DAG
function WaitForComputeNodes()
    local nodeCount = Blue.GetComputeNodeCount()
    local minNodes = 3
    if nodeCount < minNodes then
        Trigger.AfterDelay(25, WaitForComputeNodes)
        return
    end
    Log("INIT", "Compute nodes ready: " .. nodeCount)
    InitConfiguredDag()
end

-- Initialize the configured DAG (reads from IoBTConfig.dagTasks)
function InitConfiguredDag()
    if ConfiguredDagState.started then return end

    -- Apply dag settings from config if available
    ApplyDagSettings()

    -- Check if config has DAG tasks
    if not IoBTConfig.dagTasks or #IoBTConfig.dagTasks == 0 then
        print("IoBT DAG: No tasks defined in IoBTConfig.dagTasks")
        return
    end

    local nodeCount = Blue.GetComputeNodeCount()
    LogSection("DAG INITIALIZATION")
    Log("INIT", "Compute nodes: " .. nodeCount)
    Log("INIT", "Tasks: " .. #IoBTConfig.dagTasks)
    print("IoBT DAG: Found " .. nodeCount .. " compute nodes")
    print("IoBT DAG: Found " .. #IoBTConfig.dagTasks .. " tasks in config")

    if nodeCount < 1 then
        print("IoBT DAG: Need at least 1 compute node")
        return
    end

    ConfiguredDagState.started = true
    ConfiguredDagState.completedTasks = {}
    ConfiguredDagState.runningTasks = {}
    ConfiguredDagState.stalledTasks = {}
    ConfiguredDagState.taskNodeAssignment = {}
    ConfiguredDagState.pendingTransfers = {}
    ConfiguredDagState.sagaScheduleRequested = false
    ConfiguredDagState.sagaScheduleReceived = false
    ConfiguredDagState.sagaMonitorCount = 0
    ConfiguredDagState.currentPartition = nil  -- Full network, no partition restriction
    print("IoBT DAG: Starting configured DAG execution (fresh schedule)...")

    -- Register all tasks with the DAG system (read from config)
    for _, task in ipairs(IoBTConfig.dagTasks) do
        local depsStr = table.concat(task.deps or {}, ",")
        Blue.AddDagTask(task.id, task.name, depsStr)
    end

    -- Check if SAGA scheduler is available and enabled
    if ConfiguredDagState.useSagaScheduler and Blue.IsBridgeRunning() and Blue.GetBridgeConnectionCount() > 0 then
        Log("SAGA", "SAGA connected, requesting HEFT schedule")
        LogNetworkState()
        print("IoBT DAG: SAGA scheduler connected, requesting schedule...")
        RequestSagaSchedule()
        StartScheduleMonitor()
    else
        if ConfiguredDagState.useSagaScheduler then
            Log("SAGA", "SAGA not connected, using round-robin fallback")
            print("IoBT DAG: SAGA not connected (bridge=" .. tostring(Blue.IsBridgeRunning()) ..
                  ", clients=" .. Blue.GetBridgeConnectionCount() .. "), using round-robin")
        else
            Log("SAGA", "SAGA disabled, using round-robin")
            print("IoBT DAG: SAGA disabled, using round-robin")
        end
        Blue.SetSchedulerAlgorithm("Round-Robin")
        FallbackAssignTaskNodes()
        ExecuteNextDagTasks()
    end

    -- Start periodic connectivity check for stalled tasks
    StartConnectivityMonitor()
    LogStateSnapshot("After Init")
end

-- ============================================
-- SAGA Scheduler Integration
-- ============================================

-- Simple JSON encoder for Lua tables
function EncodeJson(value, indent)
    indent = indent or ""
    local valueType = type(value)

    if valueType == "nil" then
        return "null"
    elseif valueType == "boolean" then
        return value and "true" or "false"
    elseif valueType == "number" then
        return tostring(value)
    elseif valueType == "string" then
        local escaped = value:gsub('\\', '\\\\'):gsub('"', '\\"'):gsub('\n', '\\n'):gsub('\r', '\\r'):gsub('\t', '\\t')
        return '"' .. escaped .. '"'
    elseif valueType == "table" then
        local isArray = true
        local maxIndex = 0
        for k, v in pairs(value) do
            if type(k) ~= "number" or k < 1 or math.floor(k) ~= k then
                isArray = false
                break
            end
            if k > maxIndex then maxIndex = k end
        end
        if maxIndex ~= #value then isArray = false end

        if isArray then
            local parts = {}
            for i, v in ipairs(value) do
                table.insert(parts, EncodeJson(v, indent))
            end
            return "[" .. table.concat(parts, ",") .. "]"
        else
            local parts = {}
            for k, v in pairs(value) do
                local key = type(k) == "string" and k or tostring(k)
                table.insert(parts, '"' .. key .. '":' .. EncodeJson(v, indent))
            end
            return "{" .. table.concat(parts, ",") .. "}"
        end
    end
    return "null"
end

-- Build DAG JSON for SAGA scheduler (reads from IoBTConfig.dagTasks)
function BuildDagJson()
    local nodeCount = Blue.GetComputeNodeCount()

    local dag = {
        tasks = {},
        edges = {},
        compute_nodes = nodeCount,
        task_duration = ConfiguredDagState.taskDuration,
        transfer_duration = ConfiguredDagState.transferDuration
    }

    -- Add tasks with compute cost (read from config)
    for _, task in ipairs(IoBTConfig.dagTasks) do
        table.insert(dag.tasks, {
            id = task.id,
            name = task.name,
            compute_cost = task.computeCost or ConfiguredDagState.taskDuration
        })
    end

    -- Add edges (dependencies) with data size
    for _, task in ipairs(IoBTConfig.dagTasks) do
        for _, dep in ipairs(task.deps or {}) do
            table.insert(dag.edges, {
                source = dep,
                target = task.id,
                data_size = task.dataSize or ConfiguredDagState.transferDuration
            })
        end
    end

    return EncodeJson(dag)
end

-- Request schedule from SAGA service
function RequestSagaSchedule()
    if ConfiguredDagState.sagaScheduleRequested then
        return
    end

    local dagJson = BuildDagJson()
    print("IoBT DAG: Sending schedule request to SAGA...")

    Blue.RequestSchedule(dagJson)
    ConfiguredDagState.sagaScheduleRequested = true
end

-- Fallback to round-robin assignment when SAGA not available
function FallbackAssignTaskNodes()
    local nodeCount = Blue.GetComputeNodeCount()
    local nodeIndex = 0

    for _, task in ipairs(IoBTConfig.dagTasks) do
        local taskId = task.id
        if ConfiguredDagState.taskNodeAssignment[taskId] == nil then
            local assignedNode = nodeIndex % nodeCount
            nodeIndex = nodeIndex + 1
            ConfiguredDagState.taskNodeAssignment[taskId] = assignedNode
        end
    end
end

-- Monitor for SAGA schedule response
function StartScheduleMonitor()
    Trigger.AfterDelay(5, function()
        if not ConfiguredDagState.started then return end
        if ConfiguredDagState.sagaScheduleReceived then return end

        -- Check if SAGA response arrived
        if Blue.HasPendingSchedule() then
            print("IoBT DAG: SAGA schedule response received!")
            ApplySagaAssignments()
            return
        end

        -- Timeout after ~5 seconds (125 ticks at 25 tps)
        ConfiguredDagState.sagaMonitorCount = ConfiguredDagState.sagaMonitorCount + 1
        if ConfiguredDagState.sagaMonitorCount > 25 then
            print("IoBT DAG: SAGA timeout, falling back to round-robin")
            Blue.SetSchedulerAlgorithm("Round-Robin (timeout)")
            Blue.ClearPendingSchedule()
            FallbackAssignTaskNodes()
            ExecuteNextDagTasks()
            return
        end

        -- Continue monitoring
        StartScheduleMonitor()
    end)
end

-- Apply assignments from SAGA schedule response
function ApplySagaAssignments()
    local assignmentsStr = Blue.GetAllPendingAssignments()
    Log("SAGA", "Received HEFT response")
    print("IoBT DAG: Raw assignments from SAGA: " .. assignmentsStr)

    if assignmentsStr == "" then
        Log("SAGA", "Empty response, using round-robin fallback")
        print("IoBT DAG: No assignments from SAGA, using fallback")
        Blue.SetSchedulerAlgorithm("Round-Robin (empty)")
        FallbackAssignTaskNodes()
        ExecuteNextDagTasks()
        return
    end

    -- Parse "taskId:nodeIndex,taskId:nodeIndex,..." format
    local assignmentCount = 0
    local assignments = {}
    for pair in string.gmatch(assignmentsStr, "[^,]+") do
        local taskId, nodeIndexStr = string.match(pair, "([^:]+):(%d+)")
        if taskId and nodeIndexStr then
            local nodeIndex = tonumber(nodeIndexStr)
            ConfiguredDagState.taskNodeAssignment[taskId] = nodeIndex
            table.insert(assignments, taskId .. "->C" .. nodeIndex)
            print("IoBT DAG: SAGA assigned " .. taskId .. " to C" .. nodeIndex)
            assignmentCount = assignmentCount + 1
        end
    end

    if assignmentCount > 0 then
        Log("SAGA", "HEFT assignments: " .. table.concat(assignments, ", "))
        print("IoBT DAG: Applied " .. assignmentCount .. " SAGA assignments")
        Blue.SetSchedulerAlgorithm("SAGA (HEFT)")
        ConfiguredDagState.sagaScheduleReceived = true
    else
        Log("SAGA", "Parse failed, using round-robin fallback")
        print("IoBT DAG: Failed to parse SAGA assignments, using fallback")
        Blue.SetSchedulerAlgorithm("Round-Robin (parse error)")
        FallbackAssignTaskNodes()
    end

    -- Now start executing tasks
    ExecuteNextDagTasks()
end

-- ============================================
-- DAG Execution Functions
-- ============================================

-- Check if a task's dependencies are satisfied (all completed)
function AreDependenciesSatisfied(taskId)
    for _, task in ipairs(IoBTConfig.dagTasks) do
        if task.id == taskId then
            for _, dep in ipairs(task.deps or {}) do
                if not ConfiguredDagState.completedTasks[dep] then
                    return false
                end
            end
            return true
        end
    end
    return true
end

-- Check if all parent task nodes are connected to the target node
function CanAssignToNode(taskId, targetNode)
    for _, task in ipairs(IoBTConfig.dagTasks) do
        if task.id == taskId then
            for _, dep in ipairs(task.deps or {}) do
                local parentNode = ConfiguredDagState.taskNodeAssignment[dep]
                if parentNode ~= nil then
                    if not Blue.AreNodesConnected(parentNode, targetNode) then
                        return false, dep, parentNode
                    end
                end
            end
            return true, nil, nil
        end
    end
    return true, nil, nil
end

-- Find all nodes in the same partition as the given node (BFS)
function FindNodesInPartition(startNode)
    local nodeCount = Blue.GetComputeNodeCount()
    local visited = {}
    local partition = {}
    local queue = {startNode}
    visited[startNode] = true

    while #queue > 0 do
        local current = table.remove(queue, 1)
        table.insert(partition, current)

        for i = 0, nodeCount - 1 do
            if not visited[i] and Blue.AreNodesConnected(current, i) then
                visited[i] = true
                table.insert(queue, i)
            end
        end
    end

    return partition
end

-- Find the largest connected partition among all compute nodes
function FindLargestPartition()
    local nodeCount = Blue.GetComputeNodeCount()
    local visited = {}
    local largestPartition = {}

    for startNode = 0, nodeCount - 1 do
        if not visited[startNode] then
            local partition = FindNodesInPartition(startNode)
            for _, node in ipairs(partition) do
                visited[node] = true
            end
            if #partition > #largestPartition then
                largestPartition = partition
            end
        end
    end

    return largestPartition
end

-- Find a node in the same partition as the parent task
function FindNodeInParentPartition(taskId)
    -- Get the parent tasks
    for _, task in ipairs(IoBTConfig.dagTasks) do
        if task.id == taskId then
            for _, dep in ipairs(task.deps or {}) do
                local parentNode = ConfiguredDagState.taskNodeAssignment[dep]
                if parentNode ~= nil then
                    -- Find all nodes in parent's partition
                    local partition = FindNodesInPartition(parentNode)
                    if #partition > 0 then
                        -- Return the parent node itself (simplest choice)
                        return parentNode, partition
                    end
                end
            end
            break
        end
    end
    return nil, {}
end

-- Pre-assign nodes to tasks using round-robin (fallback)
function PreAssignTaskNodes()
    local nodeCount = Blue.GetComputeNodeCount()
    local nodeIndex = 0

    for _, task in ipairs(IoBTConfig.dagTasks) do
        local taskId = task.id
        if ConfiguredDagState.taskNodeAssignment[taskId] == nil then
            local assignedNode = nodeIndex % nodeCount
            nodeIndex = nodeIndex + 1
            ConfiguredDagState.taskNodeAssignment[taskId] = assignedNode
        end
    end
end

-- Find and execute tasks that are ready
function ExecuteNextDagTasks()
    local nodeCount = Blue.GetComputeNodeCount()

    -- If using SAGA and haven't received schedule yet, wait
    if ConfiguredDagState.useSagaScheduler and ConfiguredDagState.sagaScheduleRequested and not ConfiguredDagState.sagaScheduleReceived then
        print("IoBT DAG: Waiting for SAGA schedule...")
        return
    end

    -- Pre-assign any remaining tasks
    PreAssignTaskNodes()

    for _, task in ipairs(IoBTConfig.dagTasks) do
        local taskId = task.id

        local shouldSkip = ConfiguredDagState.completedTasks[taskId] or
                          ConfiguredDagState.runningTasks[taskId] or
                          ConfiguredDagState.stalledTasks[taskId]

        if not shouldSkip then
            if AreDependenciesSatisfied(taskId) then
                local assignedNode = ConfiguredDagState.taskNodeAssignment[taskId]
                local canAssign, blockedBy, blockedNode = CanAssignToNode(taskId, assignedNode)

                if canAssign then
                    Log("TASK", taskId .. " STARTED on C" .. assignedNode)
                    print("IoBT DAG: Assigning " .. taskId .. " to node C" .. assignedNode)
                    Blue.AssignTask(taskId, assignedNode)
                    ConfiguredDagState.runningTasks[taskId] = true

                    local taskDuration = ConfiguredDagState.taskDuration
                    Trigger.AfterDelay(taskDuration, function()
                        CompleteTask(taskId)
                    end)
                else
                    -- Check current mode
                    local mode = Blue.GetResilienceMode()

                    if mode == "S" then
                        -- S mode: reassign to a node in parent's partition
                        -- This means the task runs where its data already exists (no cross-partition transfer)
                        local newNode, partition = FindNodeInParentPartition(taskId)
                        if newNode ~= nil then
                            Log("REASSIGN", taskId .. " C" .. assignedNode .. "->C" .. newNode .. " (S mode, parent partition)")
                            print("IoBT DAG: [S-MODE] " .. taskId .. ": REASSIGNED C" .. assignedNode ..
                                  " -> C" .. newNode .. " (runs where parent data exists, no partition crossing)")

                            -- Update assignment and start task
                            ConfiguredDagState.taskNodeAssignment[taskId] = newNode
                            Blue.AssignTask(taskId, newNode)
                            ConfiguredDagState.runningTasks[taskId] = true

                            local taskDuration = ConfiguredDagState.taskDuration
                            Trigger.AfterDelay(taskDuration, function()
                                CompleteTask(taskId)
                            end)
                        else
                            -- No partition found, stall
                            Log("STALL", taskId .. "@C" .. assignedNode .. " no partition (S mode)")
                            Blue.StallTask(taskId)
                            ConfiguredDagState.stalledTasks[taskId] = true
                        end
                    else
                        -- B mode: stall and wait
                        Log("STALL", taskId .. "@C" .. assignedNode .. " blocked by " .. blockedBy .. "@C" .. blockedNode .. " (B mode)")
                        print("IoBT DAG: [B] Task " .. taskId .. " stalled - C" .. assignedNode ..
                              " disconnected from parent " .. blockedBy .. " (C" .. blockedNode .. ")")
                        Blue.StallTask(taskId)
                        ConfiguredDagState.stalledTasks[taskId] = true
                        LogStateSnapshot("Task Stalled")
                    end
                end
            end
        end
    end
end

-- Periodically check if stalled tasks can resume (and handle mode changes)
function StartConnectivityMonitor()
    Trigger.AfterDelay(25, function()
        if not ConfiguredDagState.started then return end

        -- Check for mode changes
        if Blue.ConsumeResilienceModeChanged() then
            local mode = Blue.GetResilienceMode()
            Log("MODE", "Changed to " .. mode)
            LogStateSnapshot("Mode Changed to " .. mode)

            -- Handle mode-specific behavior
            if mode == "H" then
                -- H mode: restart DAG on largest partition with fresh HEFT schedule
                HandleHModeRestart()
            elseif mode == "S" then
                -- S mode: try to reassign stalled tasks immediately
                HandleStalledTasksInSMode()
            elseif mode == "B" then
                -- B mode (Baseline): restart DAG with fresh HEFT schedule on full network
                HandleBaselineRestart()
            end
        end

        -- Periodic state snapshot
        MaybeLogPeriodicSnapshot()

        -- Check stalled tasks for connectivity restoration (B mode) or reassignment (S mode)
        local mode = Blue.GetResilienceMode()
        local stalledCopy = {}
        for taskId, _ in pairs(ConfiguredDagState.stalledTasks) do
            stalledCopy[taskId] = true
        end

        for taskId, _ in pairs(stalledCopy) do
            local targetNode = ConfiguredDagState.taskNodeAssignment[taskId]
            if targetNode then
                local canAssign, _, _ = CanAssignToNode(taskId, targetNode)
                if canAssign then
                    -- Connectivity restored, resume task
                    Log("UNSTALL", taskId .. " connectivity restored, resuming on C" .. targetNode)
                    print("IoBT DAG: Task " .. taskId .. " connectivity restored, resuming on C" .. targetNode)
                    Blue.UnstallTask(taskId)
                    ConfiguredDagState.stalledTasks[taskId] = nil

                    Blue.AssignTask(taskId, targetNode)
                    ConfiguredDagState.runningTasks[taskId] = true

                    local taskDuration = ConfiguredDagState.taskDuration
                    Trigger.AfterDelay(taskDuration, function()
                        CompleteTask(taskId)
                    end)
                end
            end
        end

        StartConnectivityMonitor()
    end)
end

-- Handle stalled tasks when switching to S mode
function HandleStalledTasksInSMode()
    local stalledCopy = {}
    for taskId, _ in pairs(ConfiguredDagState.stalledTasks) do
        stalledCopy[taskId] = true
    end

    for taskId, _ in pairs(stalledCopy) do
        local newNode, partition = FindNodeInParentPartition(taskId)
        if newNode ~= nil then
            local oldNode = ConfiguredDagState.taskNodeAssignment[taskId]
            Log("REASSIGN", taskId .. " C" .. tostring(oldNode) .. "->C" .. newNode .. " (S mode switch)")
            print("IoBT DAG: [S-MODE] " .. taskId .. ": REASSIGNED C" .. tostring(oldNode) ..
                  " -> C" .. newNode .. " (runs where parent data exists)")

            -- Clear stall and reassign
            Blue.UnstallTask(taskId)
            ConfiguredDagState.stalledTasks[taskId] = nil
            ConfiguredDagState.taskNodeAssignment[taskId] = newNode

            Blue.AssignTask(taskId, newNode)
            ConfiguredDagState.runningTasks[taskId] = true

            local taskDuration = ConfiguredDagState.taskDuration
            Trigger.AfterDelay(taskDuration, function()
                CompleteTask(taskId)
            end)
        end
    end
end

-- Handle H mode: restart entire DAG on largest connected partition
-- Uses HEFT scheduling restricted to partition nodes if SAGA is available
function HandleHModeRestart()
    local partition = FindLargestPartition()
    if #partition == 0 then
        Log("H-MODE", "No connected partition found!")
        print("IoBT DAG: [H] No connected partition found!")
        return
    end

    local partitionStr = {}
    for _, node in ipairs(partition) do
        table.insert(partitionStr, "C" .. node)
    end
    Log("H-MODE", "Restarting DAG on partition: " .. table.concat(partitionStr, ", "))
    print("IoBT DAG: [H] Restarting DAG on partition with " .. #partition .. " nodes: " .. table.concat(partitionStr, ", "))

    -- Clear all current DAG state
    Blue.ClearDag()
    Blue.ClearActiveLinks()
    ConfiguredDagState.completedTasks = {}
    ConfiguredDagState.runningTasks = {}
    ConfiguredDagState.stalledTasks = {}
    ConfiguredDagState.taskNodeAssignment = {}
    ConfiguredDagState.pendingTransfers = {}
    ConfiguredDagState.sagaScheduleRequested = false
    ConfiguredDagState.sagaScheduleReceived = false
    ConfiguredDagState.sagaMonitorCount = 0
    Blue.ClearPendingSchedule()

    -- Store partition for use by schedule handlers
    ConfiguredDagState.currentPartition = partition

    -- Re-register all tasks
    for _, task in ipairs(IoBTConfig.dagTasks) do
        local depsStr = table.concat(task.deps or {}, ",")
        Blue.AddDagTask(task.id, task.name, depsStr)
    end

    -- Try to use SAGA for partition-aware HEFT scheduling
    if ConfiguredDagState.useSagaScheduler and Blue.IsBridgeRunning() and Blue.GetBridgeConnectionCount() > 0 then
        Log("H-MODE", "Requesting HEFT schedule for partition")
        print("IoBT DAG: [H] Requesting HEFT schedule restricted to partition nodes...")
        -- Request fresh schedule - SAGA will use current connectivity which reflects partition
        RequestSagaSchedule()
        StartPartitionScheduleMonitor(partition)
    else
        -- Fallback: round-robin on partition nodes only
        Log("H-MODE", "SAGA not available, using round-robin on partition")
        print("IoBT DAG: [H] SAGA not connected, using round-robin on partition")
        AssignTasksToPartition(partition)
        Blue.SetSchedulerAlgorithm("Round-Robin (H-mode partition)")
        ExecuteNextDagTasks()
    end
end

-- Assign tasks to partition nodes using round-robin
function AssignTasksToPartition(partition)
    local nodeIndex = 0
    for _, task in ipairs(IoBTConfig.dagTasks) do
        local taskId = task.id
        local assignedNode = partition[(nodeIndex % #partition) + 1]  -- Lua is 1-indexed
        nodeIndex = nodeIndex + 1
        ConfiguredDagState.taskNodeAssignment[taskId] = assignedNode
        Log("H-MODE", taskId .. " assigned to C" .. assignedNode)
    end
end

-- Monitor for SAGA schedule response in H-mode (partition-aware)
function StartPartitionScheduleMonitor(partition)
    Trigger.AfterDelay(5, function()
        if not ConfiguredDagState.started then return end
        if ConfiguredDagState.sagaScheduleReceived then return end

        -- Check if SAGA response arrived
        if Blue.HasPendingSchedule() then
            print("IoBT DAG: [H] SAGA schedule response received!")
            ApplyPartitionAwareAssignments(partition)
            return
        end

        -- Timeout after ~5 seconds (125 ticks at 25 tps)
        ConfiguredDagState.sagaMonitorCount = ConfiguredDagState.sagaMonitorCount + 1
        if ConfiguredDagState.sagaMonitorCount > 25 then
            print("IoBT DAG: [H] SAGA timeout, falling back to round-robin on partition")
            Blue.SetSchedulerAlgorithm("Round-Robin (H-mode timeout)")
            Blue.ClearPendingSchedule()
            AssignTasksToPartition(partition)
            ExecuteNextDagTasks()
            return
        end

        -- Continue monitoring
        StartPartitionScheduleMonitor(partition)
    end)
end

-- Apply SAGA assignments but remap to partition nodes if needed
function ApplyPartitionAwareAssignments(partition)
    local assignmentsStr = Blue.GetAllPendingAssignments()
    Log("H-MODE", "Received HEFT response for partition")
    print("IoBT DAG: [H] Raw assignments from SAGA: " .. assignmentsStr)

    if assignmentsStr == "" then
        Log("H-MODE", "Empty response, using round-robin on partition")
        print("IoBT DAG: [H] No assignments from SAGA, using round-robin on partition")
        Blue.SetSchedulerAlgorithm("Round-Robin (H-mode empty)")
        AssignTasksToPartition(partition)
        ExecuteNextDagTasks()
        return
    end

    -- Build set of partition nodes for quick lookup
    local partitionSet = {}
    for _, node in ipairs(partition) do
        partitionSet[node] = true
    end

    -- Parse assignments and remap any out-of-partition nodes
    local assignmentCount = 0
    local assignments = {}
    local remappedCount = 0
    local partitionIndex = 1

    for pair in string.gmatch(assignmentsStr, "[^,]+") do
        local taskId, nodeIndexStr = string.match(pair, "([^:]+):(%d+)")
        if taskId and nodeIndexStr then
            local nodeIndex = tonumber(nodeIndexStr)

            -- Check if assigned node is in partition
            if partitionSet[nodeIndex] then
                ConfiguredDagState.taskNodeAssignment[taskId] = nodeIndex
                table.insert(assignments, taskId .. "->C" .. nodeIndex)
            else
                -- Remap to a partition node (round-robin among partition)
                local remappedNode = partition[(partitionIndex % #partition) + 1]
                partitionIndex = partitionIndex + 1
                ConfiguredDagState.taskNodeAssignment[taskId] = remappedNode
                table.insert(assignments, taskId .. "->C" .. remappedNode .. "(remapped)")
                remappedCount = remappedCount + 1
            end
            assignmentCount = assignmentCount + 1
        end
    end

    if assignmentCount > 0 then
        Log("H-MODE", "HEFT assignments: " .. table.concat(assignments, ", "))
        if remappedCount > 0 then
            print("IoBT DAG: [H] Applied " .. assignmentCount .. " assignments (" .. remappedCount .. " remapped to partition)")
        else
            print("IoBT DAG: [H] Applied " .. assignmentCount .. " SAGA assignments")
        end
        Blue.SetSchedulerAlgorithm("SAGA HEFT (H-mode partition)")
        ConfiguredDagState.sagaScheduleReceived = true
    else
        Log("H-MODE", "Parse failed, using round-robin on partition")
        print("IoBT DAG: [H] Failed to parse SAGA assignments, using round-robin on partition")
        Blue.SetSchedulerAlgorithm("Round-Robin (H-mode parse error)")
        AssignTasksToPartition(partition)
    end

    -- Now start executing tasks
    ExecuteNextDagTasks()
end

-- Handle Baseline mode: restart DAG with fresh HEFT schedule on full network
-- This ensures baseline always uses latest network state for scheduling
function HandleBaselineRestart()
    Log("B-MODE", "Restarting DAG with fresh HEFT schedule on full network")
    print("IoBT DAG: [B] Restarting DAG with fresh HEFT schedule...")

    -- Clear all current DAG state
    Blue.ClearDag()
    Blue.ClearActiveLinks()
    ConfiguredDagState.completedTasks = {}
    ConfiguredDagState.runningTasks = {}
    ConfiguredDagState.stalledTasks = {}
    ConfiguredDagState.taskNodeAssignment = {}
    ConfiguredDagState.pendingTransfers = {}
    ConfiguredDagState.sagaScheduleRequested = false
    ConfiguredDagState.sagaScheduleReceived = false
    ConfiguredDagState.sagaMonitorCount = 0
    ConfiguredDagState.currentPartition = nil  -- Clear partition restriction
    Blue.ClearPendingSchedule()

    -- Re-register all tasks
    for _, task in ipairs(IoBTConfig.dagTasks) do
        local depsStr = table.concat(task.deps or {}, ",")
        Blue.AddDagTask(task.id, task.name, depsStr)
    end

    -- Request fresh HEFT schedule with current network state
    if ConfiguredDagState.useSagaScheduler and Blue.IsBridgeRunning() and Blue.GetBridgeConnectionCount() > 0 then
        Log("B-MODE", "Requesting fresh HEFT schedule")
        print("IoBT DAG: [B] Requesting fresh HEFT schedule with current network state...")
        RequestSagaSchedule()
        StartScheduleMonitor()
    else
        Log("B-MODE", "SAGA not available, using round-robin")
        print("IoBT DAG: [B] SAGA not connected, using round-robin")
        Blue.SetSchedulerAlgorithm("Round-Robin (Baseline)")
        FallbackAssignTaskNodes()
        ExecuteNextDagTasks()
    end
end

-- Find all tasks that depend on the given task
function FindDependentTasks(completedTaskId)
    local dependents = {}
    for _, task in ipairs(IoBTConfig.dagTasks) do
        for _, dep in ipairs(task.deps or {}) do
            if dep == completedTaskId then
                table.insert(dependents, task.id)
                break
            end
        end
    end
    return dependents
end

-- Start data transfers from completed task to its dependent tasks
-- BUG FIX: Only visualize transfers to nodes that are actually connected
function StartDataTransfers(completedTaskId)
    local sourceNode = ConfiguredDagState.taskNodeAssignment[completedTaskId]
    if sourceNode == nil then return end

    local dependents = FindDependentTasks(completedTaskId)
    local transfersStarted = 0
    local blockedTransfers = 0

    for _, depTaskId in ipairs(dependents) do
        if not ConfiguredDagState.completedTasks[depTaskId] then
            local targetNode = ConfiguredDagState.taskNodeAssignment[depTaskId]

            if targetNode ~= nil and targetNode ~= sourceNode then
                -- BUG FIX: Check connectivity before visualizing transfer
                if Blue.AreNodesConnected(sourceNode, targetNode) then
                    print("IoBT DAG: Transferring data " .. completedTaskId .. " -> " .. depTaskId ..
                          " (C" .. sourceNode .. " -> C" .. targetNode .. ")")
                    Blue.AddTaskTransferWithNodes(completedTaskId, depTaskId, sourceNode, targetNode, "data")
                    transfersStarted = transfersStarted + 1

                    if not ConfiguredDagState.pendingTransfers[depTaskId] then
                        ConfiguredDagState.pendingTransfers[depTaskId] = {}
                    end
                    table.insert(ConfiguredDagState.pendingTransfers[depTaskId], completedTaskId)
                else
                    -- Nodes are disconnected - transfer blocked
                    Log("TRANSFER", completedTaskId .. "->" .. depTaskId .. " BLOCKED (C" .. sourceNode ..
                        " disconnected from C" .. targetNode .. ")")
                    print("IoBT DAG: Transfer " .. completedTaskId .. " -> " .. depTaskId ..
                          " blocked - nodes disconnected")
                    blockedTransfers = blockedTransfers + 1
                end
            elseif targetNode ~= nil and targetNode == sourceNode then
                -- Same node, no transfer needed - just log
                Log("TRANSFER", completedTaskId .. "->" .. depTaskId .. " local (same node C" .. sourceNode .. ")")
            end
        end
    end

    if transfersStarted > 0 then
        Trigger.AfterDelay(ConfiguredDagState.transferDuration, function()
            Blue.ClearActiveLinks()
            ExecuteNextDagTasks()
        end)
    else
        ExecuteNextDagTasks()
    end
end

-- Mark a task as complete and trigger dependent tasks
function CompleteTask(taskId)
    if ConfiguredDagState.completedTasks[taskId] then
        return
    end

    local node = ConfiguredDagState.taskNodeAssignment[taskId]
    Log("TASK", taskId .. " COMPLETED on C" .. tostring(node))
    print("IoBT DAG: " .. taskId .. " complete")
    Blue.CompleteTask(taskId)
    ConfiguredDagState.completedTasks[taskId] = true
    ConfiguredDagState.runningTasks[taskId] = nil

    local allDone = true
    for _, task in ipairs(IoBTConfig.dagTasks) do
        if not ConfiguredDagState.completedTasks[task.id] then
            allDone = false
            break
        end
    end

    if allDone then
        LogSection("DAG COMPLETE")
        LogDagState()
        print("IoBT DAG: All tasks complete! Restarting in 3 seconds...")
        Blue.ClearActiveLinks()
        Trigger.AfterDelay(75, function()
            RestartDag()
        end)
    else
        StartDataTransfers(taskId)
    end
end

-- Restart the DAG execution
function RestartDag()
    print("IoBT DAG: Restarting DAG...")
    Blue.ClearDag()
    Blue.ClearActiveLinks()
    ConfiguredDagState.started = false
    ConfiguredDagState.completedTasks = {}
    ConfiguredDagState.runningTasks = {}
    ConfiguredDagState.stalledTasks = {}
    ConfiguredDagState.taskNodeAssignment = {}
    ConfiguredDagState.pendingTransfers = {}
    ConfiguredDagState.sagaScheduleRequested = false
    ConfiguredDagState.sagaScheduleReceived = false
    ConfiguredDagState.sagaMonitorCount = 0
    ConfiguredDagState.currentPartition = nil  -- Clear partition restriction
    Blue.ClearPendingSchedule()

    Trigger.AfterDelay(25, function()
        InitConfiguredDag()
    end)
end

-- ============================================
-- World Initialization
-- ============================================

-- Called once when the map loads
function WorldLoaded()
    -- Initialize run logging
    RunLog.startTick = DateTime.GameTime or 0
    InitRunLog()
    Log("WORLD", "World loaded")

    -- Get the Blue player
    Blue = Player.GetPlayer("Blue")

    if not Blue then
        print("ERROR: Blue player not found!")
        Log("ERROR", "Blue player not found!")
        return
    end

    -- Apply network settings (communication range) from config
    ApplyNetworkSettings()

    print("IoBT: Initializing simulation...")
    print("IoBT: Export enabled = " .. tostring(IoBTConfig.export.enabled))
    print("IoBT: Sample interval = " .. IoBTConfig.export.sampleInterval .. " ticks")
    print("IoBT: Stop after = " .. IoBTConfig.export.stopAfterTicks .. " ticks")

    -- Spawn buildings
    for _, bldg in ipairs(IoBTConfig.buildings) do
        local owner = Player.GetPlayer(bldg.owner)
        if owner then
            local actor = Actor.Create(bldg.type, true, {
                Owner = owner,
                Location = CPos.New(bldg.x, bldg.y)
            })
            IoBTState.buildings[bldg.id] = {
                actor = actor,
                config = bldg
            }
            print("IoBT: Spawned building " .. bldg.id .. " (" .. bldg.type .. ") at " .. bldg.x .. "," .. bldg.y)
        else
            print("ERROR: Owner not found for building " .. bldg.id)
        end
    end

    IoBTState.initialized = true
    Log("WORLD", "Units: " .. #IoBTConfig.units .. ", Buildings: " .. #IoBTConfig.buildings)
    print("IoBT: Initialization complete. " .. #IoBTConfig.units .. " units, " .. #IoBTConfig.buildings .. " buildings configured.")

    -- Start DAG after units have spawned (wait for compute nodes)
    Trigger.AfterDelay(200, function()
        if IoBTConfig.dagTasks and #IoBTConfig.dagTasks > 0 then
            Log("WORLD", "DAG config: " .. #IoBTConfig.dagTasks .. " tasks")
            print("IoBT: Using DAG from iobt-config.lua (" .. #IoBTConfig.dagTasks .. " tasks)")
            WaitForComputeNodes()
        else
            Log("WORLD", "No DAG tasks configured")
            print("IoBT: No DAG tasks configured")
        end
    end)
end

-- Called every game tick
function Tick()
    if not IoBTState.initialized then
        return
    end

    local currentTime = DateTime.GameTime

    -- Process each configured unit
    for _, unitDef in ipairs(IoBTConfig.units) do
        local targetPos = GetInterpolatedPosition(unitDef.waypoints, currentTime)
        local state = IoBTState.units[unitDef.id]

        if targetPos then
            if not state or not state.actor or state.actor.IsDead then
                local owner = Player.GetPlayer(unitDef.owner)
                if owner then
                    local actor = Actor.Create(unitDef.type, true, {
                        Owner = owner,
                        Location = targetPos
                    })
                    state = {
                        actor = actor,
                        lastTargetPos = targetPos,
                        config = unitDef
                    }
                    IoBTState.units[unitDef.id] = state
                    print("IoBT: Spawned unit " .. unitDef.id .. " (" .. unitDef.type .. ") at tick " .. currentTime)
                end
            elseif state.lastTargetPos.X ~= targetPos.X or state.lastTargetPos.Y ~= targetPos.Y then
                state.actor.Stop()
                state.actor.Move(targetPos)
                state.lastTargetPos = targetPos
            end
        end
    end

    -- Position recording at configured interval
    if IoBTConfig.export.enabled then
        if currentTime % IoBTConfig.export.sampleInterval == 0 then
            RecordPositions(currentTime)
        end

        if IoBTConfig.export.stopAfterTicks > 0 and currentTime >= IoBTConfig.export.stopAfterTicks then
            ExportLog()
            IoBTConfig.export.enabled = false
            print("IoBT: Simulation recording complete.")
        end
    end
end
